module.exports = {
  name: "English"
  terms:
    "browser_support": "Burnzone is not supported in your browser. Please upgrade your browser to the latest version or change your browser to Mozilla or Chrome."
    "view_separate_page": "Problems on mobile devices? View BurnZone in a separate page."
    "login": "Login"
    "login_to_comment": "Login to comment"
    "login_to_challenge": "Login to challenge"
    "login_with": "Login with"
    "signup_with": "Signup with"
    "sign_in": "Sign in"
    "sign_up": "Sign up"
    "sign_in_using": "Sign in using"
    "sign_in_already_have_account": "Already registered? <a>Sign in</a>."
    "settings": "My Settings"
    "or": "or"
    "forum-time": "Time passed since the last activity in this topic"
    "comment": "Comment"
    "comments": "Comments"
    "challenges": "Challenges"
    "questions": "Questions"
    "likes": "likes"
    "write_forum_title": "Start a new forum thread"
    "write_comment": "Voice your thoughts here..."
    "write_answer": "Enter your answer here"
    "answered": "answered"
    "submit": "Submit"
    "submit_comment": "Submit comment"
    "submit_question": "Submit question"
    "edit_comment": "Edit"
    "edit_comment_save": "Save"
    "edit_comment_cancel": "Cancel"
    "reg_and_submit_comment": "Register"
    "cancel": "Cancel"
    "sort_by": "Sorted by"
    "get_burnzone": "Get BurnZone Commenting"
    "oldest": "Oldest"
    "newest": "Newest"
    "sort_activity_rating": "Activity (Last 24 hrs)"
    "sort_latest_activity": "Latest activity"
    "points": "Points"
    "points_short": "pts"
    "answers": "Answers"
    "votes": "Votes"
    "no_points": "{value} Points"
    "reply": "Reply"
    "replied_to": "replied to {value}"
    "replied_to_challenge": "replied in challenge"
    "reply_in_challenge": "Reply in the challenge"
    "view_original": "See original comment"
    "comment_in_challenge": "Comment in the challenge"
    "challenge": "Challenge"
    "question":"Question"
    "promoted": "Promoted"
    "promote": "Promote"
    "moderate": "Moderate"
    "promote_points_1": "Promote with"
    "promote_points_2": "points"
    "promote_points_3": "Add"
    "promote_title": "Promoting will make this comment appear as the top comment to all users"
    "promoted_points_note": "Promoted for {value} pts"
    "promoted_by_moderator_note": "Promoted by moderator"
    "current_promote_points": "This comment already has {value} points towards promotion."
    "promote_points_needed": "Add at least {value} more points to promote."
    "promote_points_needed_newcomment": "Add at least {value} points to promote."
    "below_minimum_promote_points": "You must offer more points for your comment to be promoted"
    "self_promote": "Promote"
    "self_highlight": "Highlight ({value} pts)"
    "demote": "Demote"
    "demote_title": "Demoting will make this comment no longer appear at the top"
    "highlighted": "Highlighted"
    "key_point": "Key point"
    "no_all_activities": "{value} Comment(s)"
    "no_comments": "{value} comment(s)"
    "no_forum_new_comments": "{value} new"
    "no_conversations": "{value} conversation(s)"
    "no_challenges": "{value} challenge(s)"
    "no_questions": "{value} question(s)"
    "no_answers": "{value} answer(s)"
    "trusted_comments_required": "You have {value} comments. At least {req_comments} comments are required for the Trusted badge."
    "trusted_vote_ratio": "You have {upvotes} upvotes and {downvotes} downvotes, a ratio of {ratio}:1. A ratio of {req_ratio}:1 is required for the Trusted badge."
    "trusted_social_verified": "You are verified on {sites}. Verification on at least {req_count} site(s) is required for the Trusted badge."
    "trusted_social_noverified": "You are not verified on any social media site. Verification on at least {req_count} site(s) is required for the Trusted badge."
    "trusted_profile_age": "You are on this site since {since} ({age} days). At least {req_age} days are required for the Trusted badge."
    "enter_your_pv": "Enter your point of view..."
    "vs": "vs"
    "enter_fb_uid": "Enter Facebook user id here"
    "non_verified_user":"The email address of this user has not been verified"
    "logout": "Logout"
    "gravatar_profile": "Profile on Gravatar"
    "edited_days_ago": "edited {value} day(s) ago"
    "edited_hours_ago": "edited {value} hour(s) ago"
    "edited_minutes_ago": "edited {value} minute(s) ago"
    "edited_just_now": "edited just now"
    "days_ago": "{value} day(s) ago"
    "hours_ago": "{value} hour(s) ago"
    "minutes_ago": "{value} minute(s) ago"
    "days_short": "{value} d"
    "hours_short": "{value} h"
    "minutes_short": "{value} m"
    "just_now": "just now"
    "ends_in_days": "Ends in {value} day(s)"
    "ends_in_hours": "Ends in {value} hours(s)"
    "ends_in_minutes": "Ends in {value} minute(s)"
    "challenge_ended": "Ended"
    "ends_now": "Should end any minute now"
    "exact_time": "on {value}"
    "my_profile": "My Public Profile"
    "challenge_comment": "Challenger's point of view:"
    "original_comment": "Summary of point challenged:"
    "or_login_with": "or login with"
    "flag": "Flag"
    "answer": "Answer"
    "share": "Share"
    "close": "close"
    "share_challenge": "Share this challenge: "
    "share_conversation": "Share this conversation"
    "share_tw": "Share on twitter"
    "share_fb": "Share on Facebook"
    "share_mail": "Share by Email"
    "share_mail_subject": "I wanted to share this BurnZone comment with you"
    "share_mail_body": "You can find it here:"
    "error_loading": "We were not able to load this conversation."
    "error_edit_comment_notexists": "This comment does not exist or it is not approved"
    "error_edit_comment_notallowed": "You are not allowed to edit this comment"
    "error_edit_comment_notsupported": "This operation is not supported"
    "error_edit_comment_invalid_text": "Please enter a text"
    "error_embed_sitenotexists": "Invalid site name."
    "error_embed_nourl": "Invalid conversation URL."
    "error_embed_embedlocalhost": "Cannot embed a conversation on the BurnZone site."
    "error_embed_forceid": "Your BurnZone account is configured to force conversation IDs but you did not provide one."
    "error_embed_useqs": "Your BurnZone account is configured to use query string keys but you did not provide all of them."
    "error_embed_url_not_reachable": "Your article must be publicly accessible on the internet."
    "error_embed_siterequired": "The site name is not configured."
    "error_embed_forum_not_enabled": "Forums are not enabled."
    "notenoughpoints": "You don't have enough points to perform that action"
    "error_share_fb": "There was an error sharing on Facebook: {error}"
    "info_share_fb": "Successfully shared on Facebook: {text}"
    "error_share_tw": "There was an error sharing on Twitter: {error}"
    "info_share_tw": "Successfully shared on Twitter: {text}"
    "started": "Started"
    "flagged": "Flagged"
    "flagged_challenge": "This challenge has been flagged"
    "change_image": "Set your image"
    "change_your_data": "Change your profile data"
    "change_name": "Name"
    "change_email": "Email"
    "change_submit": "Change"
    "use_grav_image": "Gravatar"
    "use_fb_image": "Facebook"
    "error_access_api": "There was a problem while handling your request"
    "user_banned": "You have been banned for the moment"
    "create_context_success": "Your forum topic has been successfully created"
    "create_context_approval": "Your forum topic awaits moderator approval"
    "create_comment_success": "Your comment has been successfully created"
    "create_question_success": "Your question has been successfully created"
    "create_answer_success": "Your answer has been successfully created"
    "create_comment_notallowed": "For the moment you have been banned from commenting"
    "create_comment_approval": "Your comment awaits moderator approval"
    "create_question_approval": "Your question awaits moderator approval"
    "create_answer_approval": "Your answer awaits moderator approval"
    "create_challenge_success": "Your challenge has been successfully created"
    "create_challenge_notallowed": "For the moment you have been banned from challenging comments"
    "create_challenge_approval": "Your challenge awaits moderator approval"
    "create_challenge_notpoints": "You don't have enough points to challenge this comment"
    "create_challenge_denied": "You can't challenge your own comment, a comment that does not exists, a deleted comment or a comment that has been challenged before (the challenge could be unapproved)"
    "vote_commentinch_user_in_challenge": "You can't vote because you are in the challenge"
    "vote_commentinch_once": "You can vote only once and you can retract only your previous vote"
    "vote_ch_ended": "You can't vote in a challenge that has ended"
    "like_comment_once": "You can like only once and you can retract only your previous like"
    "like_comment_retry": "There was a conflict in your request. Please retry."
    "like_comment_not_verified": "You must be verified."
    "like_comment_needs_login": "You must be logged in."
    "like_own_comment": "You cannot like your own comment"
    "like_active_competition": "You cannot dislike a comment while you participate in a competition."
    "like_author_unknown": "Someone"
    "needs_login": "You have to log in first"
    "needs_moderator": "You need moderator permissions for this"
    "user_exists": "This email address is already used by another user. Please try another one."
    "edit_profile": "You can change your name and avatar from <a href=\"{url}/profile\" target=\"_blank\">your profile page</a>"
    "delete": "Delete"
    "delete_with_points": "Delete &amp; -20pts"
    "show_in_forum": "Show in forum"
    "show_in_forum_title": "Unchecking this box will remove the thread from the forum"
    "top_answer": "Top answer"
    "social_icon_login": "If you already have a BurnZone account, click the BZ icon."
    "create_user": "Or create a BurnZone user if you haven't already signed up."
    "create_user_expl": "Creating a user will allow you to comment, vote and be part of the leaderboard."
    "challenge_cost_help": "Creating a challenge costs you profile points but you get more if you win the challenge. Only the first challenge is free."
    "anon_name": "Name"
    "anon_email": "Email"
    "anon_pass": "Password (optional)"
    "invalid_name": "Please input a name"
    "invalid_email": "Please input a valid email address"
    "invalid_password": "Please input a valid password"
    "invalid_points_value": "Please input a non-negative integer for the amount of points you are offering"
    "email_must_be_valid": "Must be valid to verify"
    "password_is_optional": "You can choose a password later"
    "site_leaderboard": "Site Leaderboard"
    "conversation_leaderboard": "Conversation Leaderboard"
    "site_leaderboard_title": "These rankings are based on all the activities users have on the entire site"
    "conversation_leaderboard_title": "These rankings are based on the activity on this single article"
    "how_to_points": "Learn how to earn points"
    "not_verified": "Your email address is not verified. You are not allowed to flag inappropriate content and you can vote for a limited number of times."
    "not_verified_marker": "Not verified"
    "notenoughpoints": "You don't have enough points to perform that action"
    "moderator_marker": "Mod"
    "trusted_marker": "Trusted"
    "trusted_marker_tooltip": "Click to see how to earn the Trusted Badge for yourself"
    "moderator_user": "This user is a moderator"
    "no_password": "You haven't set a password yet and you could lose your account. <a href=\"#{"#profile"}\">Go to your profile</a> then click \"Change password\" to set up a password for your account."
    "change_pass": "<a href=\"{url}/profile\" target=\"_blank\">Change password</a>."
    "change_notifications": "<a href=\"{url}/profile\" target=\"_blank\">Change notification options</a>."
    "change_settings": "<a href=\"{url}/profile\" target=\"_blank\"><i class=\"icon-cogs\"></i> Settings</a>"
    "subscription_options": "Subscription options"
    "subscribe": "Subscribe"
    "subscribe_articles": "Subscribe to new articles"
    "subscribe_own": "Subscribe to my own content"
    "subscribe_auto": "Auto subscribe to the conversations I take part in"
    "subscribe_conversations": "Subscribe to updates"
    "subscribe_updates": "Subscribe to updates in this conversation"
    "subscribe_success": "You have successfully subscribed"
    "unsubscribe_success": "You have successfully unsubscribed"
    "read_more": "(read more)"
    "read_less": "(read less)"
    "more_new_inv_comments": "You have {count} unseen new comments!<br><small>(click to load {inv_count} more)</small>"
    "more_new_comments": "You have {count} unseen new comments!"
    "more_inv_comments": "Click to load {inv_count} new comments!"
    "show_more": "Show more"
    "show_20_more": "Show 20 more comments"
    "show_25_more": "Show 25 more comments"
    "show_50_more": "Show 50 more comments"
    "show_all_more": "Show all"
    "delete_all": "Delete all"
    "format_text": "Formatting text"
    "select_tags_placeholder": "Select your category"
    "no_context_filter": "Select category"
    "challenge_ad_text": "Don't agree with a comment?"
    "challenge_ad_text_2": "Challenge it to receive points."
    "learn_more": "Learn More"
    "best_answer": "Best Answer"
    "best_answer_with_points": "Best Answer, {value} point(s) awarded"
    "challenged_comment": "Comment challenged"
    "challenge_cost_note": "This challenge costs {value} points"
    "challenge_free_note": "Your first challenge is free!"
    "challenged_question": "Question challenged"
    "history_back": "Go back"
    "history_back_to_forums": "Go back to forums"
    "go_to_article": "Go to article"
    "prev_activity": "Previous Activity"
    "goto_comment": "Go to this comment"
    "go_to_comments": "Go to comments"
    "is_question": "I am asking a question to the community."
    "points_offered_note": 'Offer <input type="text" class="question_points_offered" maxlength="3"/> of my points to the best answer'
    "question_view_points_offered": "{value} point(s) up for grabs"
    "comment_active_replies": "{value} users  are replying..."
    "comment_deleted": "This comment has been deleted"
    "context_deleted": "This forum topic has been deleted"
    "question_deleted": "This question has been deleted"
    "answer_deleted": "This answer has been deleted"
    "challenge_deleted": "This challenge has been deleted"
    "said": "said"
    "challenged": "challenged"
    "challenge_winner": "Challenge winner"
    "competitions": "Competitions"
    "competition_banner": "Competition: <strong>{title}</strong> from {start} to {end}; read the <a target='_blank' href='{rules}'>Rules</a> and join the conversation!</a>"
    "competition_header": "<i class='icon-trophy'></i> Win <a href='{prize_url}'>{prize}</a> by joining the {community} community and commenting between {start} - {end} (<span class='countdown'>{countdown}</span> remaining, see <a target='_blank' href='{rules}'>rules</a>)"
    "competition_header_share": "To join the competition share a comment or article."
    "competition_starts_on": "Competition starts on"
    "competition_active": "Competition is active"
    "competition_ended_on": "Competition ended on"
    "competition_active_until": "Competition active until"
    "competition_winner": "Winner"
    "competition_rules": "Rules"
    "competition_prize": "Prize"
    "competition_ranking_title": "Competition Ranking"
    "title_like_up": "Like this comment"
    "title_like_down": "Dislike this comment"
    "title_best_answer": "This is the best answer, based on votes received"
    "title_challenged": "This comment got challenged"
    "title_reply": "Reply to this comment"
    "title_challenge": "Challenge this comment to share an opposing view"
    "title_share": "Share this on social media"
    "title_flag": "Flag for spam"
    "title_vote_up": "Vote up"
    "title_vote_down": "Retract vote"
    "title_challenged_side": "This is the comment that got challenged. Vote if you agree with the commenter."
    "title_challenger_side": "This is the challenger's opinion. Vote if you agree with his opposing point of view."
    "title_reply_comment": "Comment this opinion"
    "title_reply_question": "Comment this question"
    "title_reply_answer": "Comment this answer"
    "title_reply_challenge": "Comment this challenge"
    "title_question_answer": "Answer this question"
    "title_answer_note": "This is an answer to the above question"
    "title_is_question": "Check this if you're posting a question"
    "title_points_offered": "Type how many points will the author of the best answer get"
    "title_logo": "BurnZone Commenting"
    "title_goto_comment": "Go to this comment"
    "title_input_forum_title_counter": "Remaining characters"
    "title_view_original": "View the original comment"
    "title_self_promote": "Pay points to have your comment sent to the top of the conversation"
    "title_self_highlight": "Pay points to have your comment highlighted in the conversation"
    "title_highlighted_note": "This comment is highlighted"
    "new_notifications": "{value}"
    "user_notif_NEW_CONVERSATION": "A new article was published on {sitename}"
    "user_notif_WIN_QUESTION": "You had the best answer!"
    "user_notif_WIN_QUESTION_here": "You had the best answer!"
    "user_notif_NEW_COMMENT": "New comment"
    "user_notif_NEW_COMMENT_here": "New comment"
    "user_notif_MENTION": "{username} mentioned you in a comment"
    "user_notif_ANSWER": "{username} answered your comment"
    "user_notif_ANSWER_here": "{username} answered your comment"
    "user_notif_PROMOTED_COMMENT": "Your comment has been promoted"
    "user_notif_PROMOTED_COMMENT_here": "Your comment has been promoted"
    "user_notif_OUTBID_COMMENT": "Your comment has been demoted because another user has promoted their comment with more points.  Add more points to promote your comment again."
    "user_notif_OUTBID_COMMENT_here": "Your comment has been demoted because another user has promoted their comment with more points.  Add more points to promote your comment again."
    "user_notif_REPLY": "{username} replied to your comment"
    "user_notif_REPLY_here": "{username} replied to your comment"
    "user_notif_CHALLENGED": "{username} challenged your comment"
    "user_notif_CHALLENGED_here": "{username} challenged your comment"
    "user_notif_NEW_CHALLENGE": "New challenge"
    "user_notif_NEW_CHALLENGE_here": "New challenge"
    "user_notif_WIN_CHALLENGE": "You won your challenge!"
    "user_notif_WIN_CHALLENGE_here": "You won your challenge!"
    "user_notif_LOSE_CHALLENGE": "You lost your challenge!"
    "user_notif_LOSE_CHALLENGE_here": "You lost your challenge!"
    "user_notif_VOTE": "{username} voted you in a challenge"
    "user_notif_VOTE_here": "{username} voted you in a challenge"
    "user_notif_VOTE_down": "Someone retracted the vote for you in a challenge"
    "user_notif_VOTE_down_here": "Someone retracted the vote for you in a challenge"
    "user_notif_LIKE_ANSWER": "{username} liked your answer"
    "user_notif_LIKE_ANSWER_here": "{username} liked your answer"
    "user_notif_LIKE_ANSWER_down": "Someone retracted the vote for your answer"
    "user_notif_LIKE_ANSWER_down_here": "Someone retracted the vote for your answer"
    "user_notif_LIKE_COMMENT": "{username} liked your comment"
    "user_notif_LIKE_COMMENT_here": "{username} liked your comment"
    "user_notif_LIKE_COMMENT_down": "Someone retracted the like for your comment"
    "user_notif_LIKE_COMMENT_down_here": "Someone retracted the like for your comment"
    "user_notif_LIKE_ANSWER_UPDOWN": "{username} liked your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_here": "{username} liked your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_retract": "Someone retracted the like for your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_retract_here": "Someone retracted the like for your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_down": "Someone down-liked your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_down_here": "Someone down-liked your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_down_retract": "Someone retracted the down-like for your answer"
    "user_notif_LIKE_ANSWER_UPDOWN_down_retract_here": "Someone retracted the down-like for your answer"
    "user_notif_LIKE_COMMENT_UPDOWN": "{username} liked your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_here": "{username} liked your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_retract": "Someone retracted the like for your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_retract_here": "Someone retracted the like for your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_down": "Someone down-liked your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_down_here": "Someone down-liked your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_down_retract": "Someone retracted the down-like for your comment"
    "user_notif_LIKE_COMMENT_UPDOWN_down_retract_here": "Someone retracted the down-like for your comment"
    "user_notif_COMPETITION_START": "Competition started: {title}"
    "user_notif_COMPETITION_STARTING": "{days} days until competition starts: {title}"
    "user_notif_COMPETITION_END": "Competition ended: {title}"
    "user_notif_COMPETITION_ENDING": "Competition {title} ending in {days} days"
}
